export default [
  {
    id: 25251784,
    name: 'ADVANCED TECHNIQUES IN REGIONAL ANESTHESIA',
    dateCompleted: '2018-05-13T00:00:00',
    submitterName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    hours: 2,
    licenseNumber: 'RN99999999',
    rating: null,
    hasAttachments: false,
    courseTrackingNumber: '20-453398',
    fullTrackingNumber: '10-1644606',
    entityId: 1644606,
    rosterCode: 'ROSTER',
    deliveryMethod: 'WORKSHOP',
    courseType: 'CD_LIVE',
    submittedDate: '2018-06-13T10:55:43',
    questions: [],
    attachments: [],
    providerName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    trackingPrefix: 'ProviderPost',
    idCourse: 453398,
    components: null,
    postCECreditStatus: null,
    postCourseType: null,
    expectedDateCompleted: null,
    additionalInfo: null,
    postCeCreditDocumentation: null,
    postCeCreditComments: null,
    postCeCreditSubmission: null,
    isMustFind: false
  },
  {
    id: 25251782,
    name: 'ADVANCED TECHNIQUES IN REGIONAL ANESTHESIA',
    dateCompleted: '2018-05-12T00:00:00',
    submitterName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    hours: 2,
    licenseNumber: 'RN99999999',
    rating: null,
    hasAttachments: false,
    courseTrackingNumber: '20-453398',
    fullTrackingNumber: '10-1644604',
    entityId: 1644604,
    rosterCode: 'ROSTER',
    deliveryMethod: 'WORKSHOP',
    courseType: 'CD_LIVE',
    submittedDate: '2018-06-13T10:53:37',
    questions: [],
    attachments: [],
    providerName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    trackingPrefix: 'ProviderPost',
    idCourse: 453398,
    components: null,
    postCECreditStatus: null,
    postCourseType: null,
    expectedDateCompleted: null,
    additionalInfo: null,
    postCeCreditDocumentation: null,
    postCeCreditComments: null,
    postCeCreditSubmission: null,
    isMustFind: false
  },
  {
    id: 25251780,
    name: 'ADVANCED TECHNIQUES IN REGIONAL ANESTHESIA',
    dateCompleted: '2018-05-11T00:00:00',
    submitterName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    hours: 2,
    licenseNumber: 'RN99999999',
    rating: null,
    hasAttachments: false,
    courseTrackingNumber: '20-453398',
    fullTrackingNumber: '10-1644602',
    entityId: 1644602,
    rosterCode: 'ROSTER',
    deliveryMethod: 'WORKSHOP',
    courseType: 'CD_LIVE',
    submittedDate: '2018-06-13T10:49:16',
    questions: [],
    attachments: [],
    providerName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    trackingPrefix: 'ProviderPost',
    idCourse: 453398,
    components: null,
    postCECreditStatus: null,
    postCourseType: null,
    expectedDateCompleted: null,
    additionalInfo: null,
    postCeCreditDocumentation: null,
    postCeCreditComments: null,
    postCeCreditSubmission: null,
    isMustFind: false
  },
  {
    id: 25251776,
    name: 'ADVANCED TECHNIQUES IN REGIONAL ANESTHESIA',
    dateCompleted: '2018-05-10T00:00:00',
    submitterName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    hours: 2,
    licenseNumber: 'RN99999999',
    rating: null,
    hasAttachments: false,
    courseTrackingNumber: '20-453398',
    fullTrackingNumber: '10-1644600',
    entityId: 1644600,
    rosterCode: 'ROSTER',
    deliveryMethod: 'WORKSHOP',
    courseType: 'CD_LIVE',
    submittedDate: '2018-06-13T10:46:18',
    questions: [],
    attachments: [],
    providerName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    trackingPrefix: 'ProviderPost',
    idCourse: 453398,
    components: null,
    postCECreditStatus: null,
    postCourseType: null,
    expectedDateCompleted: null,
    additionalInfo: null,
    postCeCreditDocumentation: null,
    postCeCreditComments: null,
    postCeCreditSubmission: null,
    isMustFind: false
  },
  {
    id: 25251774,
    name: 'ADVANCED TECHNIQUES IN REGIONAL ANESTHESIA',
    dateCompleted: '2018-05-09T00:00:00',
    submitterName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    hours: 2,
    licenseNumber: 'RN99999999',
    rating: null,
    hasAttachments: false,
    courseTrackingNumber: '20-453398',
    fullTrackingNumber: '10-1644598',
    entityId: 1644598,
    rosterCode: 'ROSTER',
    deliveryMethod: 'WORKSHOP',
    courseType: 'CD_LIVE',
    submittedDate: '2018-06-13T10:44:03',
    questions: [],
    attachments: [],
    providerName: 'NORTHWEST ANESTHESIA SEMINARS, INC.',
    trackingPrefix: 'ProviderPost',
    idCourse: 453398,
    components: null,
    postCECreditStatus: null,
    postCourseType: null,
    expectedDateCompleted: null,
    additionalInfo: null,
    postCeCreditDocumentation: null,
    postCeCreditComments: null,
    postCeCreditSubmission: null,
    isMustFind: false
  }
];
